services:
  - type: web
    name: finance-app
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y python3.9 python3-pip
      python3.9 -m venv venv
      source venv/bin/activate
      python3.9 -m pip install --upgrade pip
      python3.9 -m pip install -r requirements.txt
      npm install
    startCommand: npm start
